"""
Case Studies Content Module
Contains case study data
"""

from typing import List, Dict


def get_case_studies() -> List[Dict]:
    """Get list of case studies"""
    return [
        {
            "title": "RAG Copilot Implementation for Policy & Compliance Research",
            "slug": "rag-copilot-financial-compliance",
            "industry": "Regulated Enterprise",
            "client": "Top-10 U.S. enterprise (risk & compliance division)",
            "challenge": "The client needed to streamline policy interpretation, evidence gathering, and internal knowledge lookup across multiple governance frameworks. Manual processes were time-consuming and error-prone, with reviewers spending significant time searching, cross-referencing, and documenting decisions.",
            "solution": "We implemented a RAG copilot system that integrated with their existing knowledge base, providing instant access to compliance information with proper citations and evidence trails. The system included permission-aware retrieval, audit logging, and evaluation baselines.",
            "results": "Reduced compliance research time by 75%, improved accuracy of policy interpretations, and enabled real-time compliance checks.",
            "metrics": {
                "time_saved": "75%",
                "accuracy_improvement": "40%",
                "adoption_rate": "90%",
                "measurement_period": "12 weeks post-deployment",
                "methodology": "Before/after time tracking and accuracy audits",
            },
            "timeline": {
                "kickoff": "Week 1",
                "architecture_review": "Week 2",
                "build_complete": "Week 6",
                "pilot_deployment": "Week 7",
                "production_rollout": "Week 8",
                "total_duration": "8 weeks",
            },
            "architecture": {
                "components": [
                    "Vector database (Pinecone)",
                    "LLM API (OpenAI)",
                    "Permission engine",
                    "Audit logging system",
                    "Evaluation pipeline",
                ],
                "integrations": [
                    "SharePoint knowledge base",
                    "Active Directory",
                    "Compliance management system",
                ],
                "diagram": "/static/img/case-study-placeholder.jpg",
            },
            "risk_controls": {
                "audit_trails": "Complete audit logging of all queries and responses",
                "permissions": "RBAC with source-level entitlements",
                "evaluation": "Automated groundedness and citation accuracy testing",
                "compliance": "Record-keeping controls, retention support, and audit-ready traceability",
            },
            "artifacts": {
                "screenshots": ["/static/img/case-study-placeholder.jpg"],
                "sample_outputs": "Example compliance memo with citations",
                "documents": [],
            },
            "image": "/static/img/case-study-placeholder.jpg",
        },
        {
            "title": "Agent Automation for Media Content Operations",
            "slug": "agent-automation-media-content",
            "industry": "Media",
            "client": "Global Media Network",
            "challenge": "Content review and approval workflows were manual and slow, creating bottlenecks in content production pipelines. Content teams spent 40% of their time on review and approval tasks.",
            "solution": "We built an agentic automation system with human-in-the-loop checkpoints, automated content review, and intelligent routing for approval workflows. The system included brand safety checks, provenance tracking, and disclosure workflows.",
            "results": "Accelerated content production by 60%, reduced manual review time, and improved content quality through automated checks.",
            "metrics": {
                "production_speed": "60% faster",
                "review_time": "50% reduction",
                "content_quality": "25% improvement",
                "measurement_period": "16 weeks post-deployment",
                "methodology": "Production metrics tracking and quality audits",
            },
            "timeline": {
                "kickoff": "Week 1",
                "architecture_review": "Week 2",
                "build_complete": "Week 9",
                "pilot_deployment": "Week 10",
                "production_rollout": "Week 12",
                "total_duration": "12 weeks",
            },
            "architecture": {
                "components": [
                    "Agent orchestration engine",
                    "Content review API",
                    "Approval workflow system",
                    "Brand safety checker",
                    "Provenance tracker",
                ],
                "integrations": [
                    "Content management system",
                    "Slack notifications",
                    "Approval queue dashboard",
                ],
                "diagram": "/static/img/case-study-placeholder.jpg",
            },
            "risk_controls": {
                "audit_trails": "Complete audit logging of all content decisions",
                "permissions": "Role-based approval workflows",
                "evaluation": "Automated brand safety and quality scoring",
                "compliance": "Synthetic media disclosure compliance",
            },
            "artifacts": {
                "screenshots": ["/static/img/case-study-placeholder.jpg"],
                "sample_outputs": "Example approval workflow dashboard",
                "documents": [],
            },
            "image": "/static/img/case-study-placeholder.jpg",
        },
        {
            "title": "LLMOps Foundation for Enterprise AI Platform",
            "slug": "llmops-enterprise-platform",
            "industry": "Regulated Enterprise",
            "client": "Fortune 500 enterprise",
            "challenge": "Multiple AI applications lacked centralized monitoring, evaluation, and governance, making it difficult to ensure reliability and compliance. Incidents were frequent and deployments were slow due to manual processes.",
            "solution": "We established a comprehensive LLMOps foundation with evaluation pipelines, monitoring, versioning, and CI/CD gating for all AI applications. The platform included automated regression testing, prompt/model versioning, and rollback capabilities.",
            "results": "Achieved 99.9% uptime, reduced incidents by 80%, and enabled rapid iteration with confidence in production deployments.",
            "metrics": {
                "uptime": "99.9%",
                "incident_reduction": "80%",
                "deployment_speed": "3x faster",
                "measurement_period": "6 months post-deployment",
                "methodology": "Platform monitoring and incident tracking",
            },
            "timeline": {
                "kickoff": "Week 1",
                "architecture_review": "Week 2",
                "build_complete": "Week 6",
                "pilot_deployment": "Week 7",
                "production_rollout": "Week 8",
                "total_duration": "8 weeks",
            },
            "architecture": {
                "components": [
                    "Evaluation pipeline",
                    "Monitoring dashboard",
                    "Version control system",
                    "CI/CD gates",
                    "Rollback system",
                ],
                "integrations": [
                    "GitHub Actions",
                    "Datadog",
                    "Slack alerts",
                    "All AI applications",
                ],
                "diagram": "/static/img/case-study-placeholder.jpg",
            },
            "risk_controls": {
                "audit_trails": "Complete audit logging of all deployments and changes",
                "permissions": "RBAC for deployment approvals",
                "evaluation": "Automated regression testing before deployments",
                "compliance": "SOC 2-aligned controls and auditability",
            },
            "artifacts": {
                "screenshots": ["/static/img/case-study-placeholder.jpg"],
                "sample_outputs": "Example evaluation report and monitoring dashboard",
                "documents": [],
            },
            "image": "/static/img/case-study-placeholder.jpg",
        },
        {
            "title": "Production-Grade LLMOps Infrastructure",
            "slug": "llmops-infrastructure",
            "industry": "Regulated Enterprise",
            "client": "Enterprise AI Platform (Ishtar AI Case Study)",
            "challenge": "Building production-ready LLM infrastructure requires careful hardware selection, cost optimization, and scalable deployment patterns. Traditional infrastructure approaches don't account for LLM-specific requirements like GPU partitioning, token economics, and hybrid cloud deployments.",
            "solution": "We designed and implemented a comprehensive Infrastructure-as-Code (IaC) foundation using Terraform, Kubernetes orchestration for LLM workloads, and a hybrid deployment architecture. The infrastructure includes GPU partitioning for multi-tenancy, cost-optimized serving stacks, and automated scaling based on demand patterns.",
            "results": "Achieved 60% reduction in infrastructure deployment time, optimized cost per million tokens by 40%, and improved multi-cluster reliability to 99.95% uptime.",
            "metrics": {
                "deployment_time_reduction": "60%",
                "cost_optimization": "40% reduction",
                "uptime": "99.95%",
                "infrastructure_provisioning": "15 minutes",
                "measurement_period": "6 months post-deployment",
                "methodology": "Infrastructure metrics tracking and cost analysis",
            },
            "timeline": {
                "kickoff": "Week 1",
                "architecture_review": "Week 2",
                "iac_implementation": "Week 4",
                "kubernetes_setup": "Week 5",
                "serving_stack_deployment": "Week 6",
                "production_rollout": "Week 7",
                "total_duration": "7 weeks",
            },
            "architecture": {
                "components": [
                    "Infrastructure-as-Code (Terraform)",
                    "Kubernetes cluster with GPU nodes",
                    "Model serving infrastructure (vLLM/TGI)",
                    "Cost monitoring and optimization system",
                    "Multi-cluster orchestration",
                    "Hybrid cloud connectivity",
                ],
                "integrations": [
                    "Cloud provider APIs (AWS/GCP/Azure)",
                    "Kubernetes operators",
                    "Monitoring systems (Prometheus/Grafana)",
                    "Cost management tools",
                ],
                "diagram": "/static/img/case-study-placeholder.jpg",
            },
            "risk_controls": {
                "audit_trails": "Complete infrastructure change logging via IaC",
                "permissions": "RBAC for infrastructure access and modifications",
                "evaluation": "Automated infrastructure testing and validation",
                "compliance": "SOC 2-aligned infrastructure controls and auditability",
            },
            "artifacts": {
                "screenshots": ["/static/img/case-study-placeholder.jpg"],
                "sample_outputs": "Infrastructure architecture diagrams and cost analysis reports",
                "documents": [],
            },
            "image": "/static/img/case-study-placeholder.jpg",
            "book_reference": {
                "title": "Advanced Large Language Model Operations",
                "author": "David Stroud",
                "publisher": "Springer Nature",
                "year": "2026",
                "chapter": "Chapter 3: Infrastructure and Environment for LLMOps",
            },
        },
        {
            "title": "Continuous Evaluation & CI/CD for LLM Systems",
            "slug": "continuous-evaluation-cicd",
            "industry": "Regulated Enterprise",
            "client": "Enterprise AI Platform (Ishtar AI Case Study)",
            "challenge": "LLM systems require continuous evaluation to catch regressions and hallucinations, but traditional CI/CD pipelines don't account for non-deterministic model behavior. Deployments were risky without proper evaluation gates, leading to production incidents.",
            "solution": "We implemented a comprehensive continuous evaluation pipeline with model-graded evaluation (LLM-as-Judge), regression testing, and automated CI/CD gates. The system includes canary deployments, automated rollback capabilities, and structured prompt testing for multi-agent systems.",
            "results": "Achieved 95% regression detection rate, improved deployment confidence by 80%, and reduced release cycle time by 50% while maintaining production stability.",
            "metrics": {
                "regression_detection": "95%",
                "deployment_confidence": "80% improvement",
                "release_cycle_reduction": "50%",
                "production_incidents": "90% reduction",
                "measurement_period": "8 months post-deployment",
                "methodology": "CI/CD metrics tracking and incident analysis",
            },
            "timeline": {
                "kickoff": "Week 1",
                "evaluation_pipeline_design": "Week 2",
                "ci_cd_integration": "Week 4",
                "canary_deployment_setup": "Week 5",
                "rollback_automation": "Week 6",
                "production_rollout": "Week 7",
                "total_duration": "7 weeks",
            },
            "architecture": {
                "components": [
                    "Continuous evaluation pipeline",
                    "Model-graded evaluation system (LLM-as-Judge)",
                    "Regression testing framework",
                    "Canary deployment controller",
                    "Automated rollback system",
                    "Structured prompt testing",
                ],
                "integrations": [
                    "GitHub Actions",
                    "Argo Rollouts",
                    "Evaluation harness",
                    "Monitoring systems",
                    "Alerting systems",
                ],
                "diagram": "/static/img/case-study-placeholder.jpg",
            },
            "risk_controls": {
                "audit_trails": "Complete evaluation and deployment logging",
                "permissions": "RBAC for deployment approvals and evaluation access",
                "evaluation": "Automated regression and behavioral drift testing",
                "compliance": "Release gates aligned with compliance requirements",
            },
            "artifacts": {
                "screenshots": ["/static/img/case-study-placeholder.jpg"],
                "sample_outputs": "Example evaluation reports and CI/CD pipeline dashboards",
                "documents": [],
            },
            "image": "/static/img/case-study-placeholder.jpg",
            "book_reference": {
                "title": "Advanced Large Language Model Operations",
                "author": "David Stroud",
                "publisher": "Springer Nature",
                "year": "2026",
                "chapter": "Chapter 4: Continuous Integration and Deployment for LLM Systems",
            },
        },
        {
            "title": "Advanced Observability & Monitoring for LLM Applications",
            "slug": "observability-monitoring",
            "industry": "Regulated Enterprise",
            "client": "Enterprise AI Platform (Ishtar AI Case Study)",
            "challenge": "LLM applications require specialized monitoring beyond traditional application metrics. RAG systems need retrieval-specific metrics, prompt flows require detailed tracing, and quality degradation must be detected before user impact. Existing monitoring solutions lacked LLM-specific capabilities.",
            "solution": "We implemented a comprehensive observability stack using OpenTelemetry for standardized telemetry, RAG-specific metric design, prompt flow tracing, and real-time dashboards. The system includes automated quality checks, historical analysis capabilities, and intelligent alerting based on LLM-specific patterns.",
            "results": "Reduced mean time to detection (MTTD) by 70%, achieved 100% observability coverage across all LLM applications, and improved alert accuracy to 95% (reducing false positives by 80%).",
            "metrics": {
                "mttd_reduction": "70%",
                "observability_coverage": "100%",
                "alert_accuracy": "95%",
                "false_positive_reduction": "80%",
                "incident_resolution_time": "50% faster",
                "measurement_period": "6 months post-deployment",
                "methodology": "Monitoring metrics analysis and incident tracking",
            },
            "timeline": {
                "kickoff": "Week 1",
                "observability_design": "Week 2",
                "opentelemetry_integration": "Week 3",
                "rag_metrics_implementation": "Week 4",
                "dashboard_development": "Week 5",
                "alerting_setup": "Week 6",
                "production_rollout": "Week 7",
                "total_duration": "7 weeks",
            },
            "architecture": {
                "components": [
                    "OpenTelemetry instrumentation",
                    "RAG-specific metrics collector",
                    "Prompt flow tracer",
                    "Real-time dashboards (Grafana)",
                    "Automated quality check system",
                    "Historical analysis engine",
                ],
                "integrations": [
                    "OpenTelemetry SDK",
                    "Prometheus",
                    "Grafana",
                    "Alerting systems (PagerDuty/Slack)",
                    "All LLM applications",
                ],
                "diagram": "/static/img/case-study-placeholder.jpg",
            },
            "risk_controls": {
                "audit_trails": "Complete observability data retention and audit logging",
                "permissions": "RBAC for monitoring data access",
                "evaluation": "Automated quality checks and anomaly detection",
                "compliance": "Observability aligned with audit and compliance requirements",
            },
            "artifacts": {
                "screenshots": ["/static/img/case-study-placeholder.jpg"],
                "sample_outputs": "Example monitoring dashboards and trace visualizations",
                "documents": [],
            },
            "image": "/static/img/case-study-placeholder.jpg",
            "book_reference": {
                "title": "Advanced Large Language Model Operations",
                "author": "David Stroud",
                "publisher": "Springer Nature",
                "year": "2026",
                "chapter": "Chapter 5: Monitoring and Observability of LLM Applications",
            },
        },
        {
            "title": "Scaling LLM Production Systems",
            "slug": "scaling-production-systems",
            "industry": "Regulated Enterprise",
            "client": "Enterprise AI Platform (Ishtar AI Case Study)",
            "challenge": "Scaling LLM deployments requires sophisticated techniques beyond simple horizontal scaling. GPU partitioning, distributed inference, batching optimization, and capacity planning are critical for cost-effective scaling while maintaining latency SLOs. Traditional scaling approaches don't account for LLM-specific constraints.",
            "solution": "We implemented a comprehensive scaling solution with GPU partitioning for multi-tenancy, distributed inference using tensor and pipeline parallelism, dynamic batching optimization, and data-driven capacity planning. The system includes SLO budget management and automated scaling based on demand patterns.",
            "results": "Achieved 3x throughput improvement, reduced cost per query by 45%, and maintained 99.9% latency SLO compliance even during peak demand periods.",
            "metrics": {
                "throughput_improvement": "3x",
                "cost_per_query_reduction": "45%",
                "latency_slo_compliance": "99.9%",
                "gpu_utilization": "85% average",
                "capacity_efficiency": "60% improvement",
                "measurement_period": "6 months post-deployment",
                "methodology": "Performance metrics tracking and cost analysis",
            },
            "timeline": {
                "kickoff": "Week 1",
                "scaling_strategy_design": "Week 2",
                "gpu_partitioning_implementation": "Week 3",
                "distributed_inference_setup": "Week 4",
                "batching_optimization": "Week 5",
                "capacity_planning_system": "Week 6",
                "production_rollout": "Week 7",
                "total_duration": "7 weeks",
            },
            "architecture": {
                "components": [
                    "GPU partitioning system",
                    "Distributed inference engine",
                    "Tensor parallelism implementation",
                    "Pipeline parallelism setup",
                    "Dynamic batching optimizer",
                    "Capacity planning system",
                    "SLO budget manager",
                ],
                "integrations": [
                    "Kubernetes GPU operators",
                    "Model serving frameworks (vLLM/TGI)",
                    "Monitoring systems",
                    "Autoscaling controllers",
                ],
                "diagram": "/static/img/case-study-placeholder.jpg",
            },
            "risk_controls": {
                "audit_trails": "Complete scaling decision logging and capacity planning records",
                "permissions": "RBAC for scaling configuration and capacity changes",
                "evaluation": "Automated performance testing and SLO validation",
                "compliance": "Scaling controls aligned with operational requirements",
            },
            "artifacts": {
                "screenshots": ["/static/img/case-study-placeholder.jpg"],
                "sample_outputs": "Scaling architecture diagrams and performance analysis reports",
                "documents": [],
            },
            "image": "/static/img/case-study-placeholder.jpg",
            "book_reference": {
                "title": "Advanced Large Language Model Operations",
                "author": "David Stroud",
                "publisher": "Springer Nature",
                "year": "2026",
                "chapter": "Chapter 6: Scaling Up LLM Deployments",
            },
        },
        {
            "title": "End-to-End LLMOps Implementation",
            "slug": "end-to-end-llmops",
            "industry": "Regulated Enterprise",
            "client": "Enterprise AI Platform (Ishtar AI Case Study)",
            "challenge": "Building a complete, production-ready LLMOps platform requires integrating infrastructure, CI/CD, monitoring, scaling, and governance into a cohesive system. Each component must work together seamlessly to deliver reliable, auditable, and scalable LLM applications.",
            "solution": "We implemented a comprehensive end-to-end LLMOps platform that integrates all components: Infrastructure-as-Code foundation, continuous evaluation pipelines, advanced observability, scalable serving infrastructure, and governance frameworks. The platform provides a complete operational contract for LLM applications.",
            "results": "Delivered a production-ready LLMOps platform that supports multiple LLM applications with 99.9% uptime, comprehensive audit trails, and rapid iteration capabilities. Enabled deployment of new LLM applications in days rather than weeks.",
            "metrics": {
                "platform_uptime": "99.9%",
                "application_deployment_time": "80% reduction",
                "operational_efficiency": "3x improvement",
                "audit_readiness": "100%",
                "time_to_production": "Days vs weeks",
                "measurement_period": "12 months post-deployment",
                "methodology": "Platform metrics tracking and operational analysis",
            },
            "timeline": {
                "kickoff": "Week 1",
                "architecture_design": "Week 2-3",
                "infrastructure_setup": "Week 4-5",
                "ci_cd_implementation": "Week 6-7",
                "monitoring_setup": "Week 8-9",
                "scaling_implementation": "Week 10-11",
                "integration_testing": "Week 12",
                "production_rollout": "Week 13",
                "total_duration": "13 weeks",
            },
            "architecture": {
                "components": [
                    "Infrastructure-as-Code foundation",
                    "Kubernetes orchestration",
                    "Continuous evaluation pipelines",
                    "Advanced observability stack",
                    "Scalable serving infrastructure",
                    "Governance and compliance framework",
                    "Multi-agent system support",
                ],
                "integrations": [
                    "Cloud infrastructure",
                    "CI/CD systems",
                    "Monitoring and alerting",
                    "All LLM applications",
                    "Compliance systems",
                ],
                "diagram": "/static/img/case-study-placeholder.jpg",
            },
            "risk_controls": {
                "audit_trails": "End-to-end traceability across all components",
                "permissions": "Comprehensive RBAC across platform",
                "evaluation": "Continuous evaluation and quality gates",
                "compliance": "Complete compliance framework with auditability",
            },
            "artifacts": {
                "screenshots": ["/static/img/case-study-placeholder.jpg"],
                "sample_outputs": "Complete platform architecture and operational runbooks",
                "documents": [],
            },
            "image": "/static/img/case-study-placeholder.jpg",
            "book_reference": {
                "title": "Advanced Large Language Model Operations",
                "author": "David Stroud",
                "publisher": "Springer Nature",
                "year": "2026",
                "chapter": "Chapter 12: Case Study Conclusion - Implementing Ishtar AI End-to-End",
            },
        },
    ]


def get_case_study_by_slug(slug: str) -> Dict:
    """Get a specific case study by slug"""
    case_studies = get_case_studies()
    for case_study in case_studies:
        if case_study.get("slug") == slug:
            return case_study
    return None
